version: '3'

name: prometheus-grafana
volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config:/etc/prometheus
      - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
#  cadvisor:
#    image: gcr.io/cadvisor/cadvisor:latest
#    container_name: cadvisor
#    ports:
#    - 8080:8080
#    volumes:
#    - /:/rootfs:ro
#    - /var/run:/var/run:rw
#    - /sys:/sys:ro
#    - /var/lib/docker/:/var/lib/docker:ro
#    depends_on:
#    - redis
#  redis:
#    image: redis:latest
#    container_name: redis
#    ports:
#    - 6379:6379
#  snmp_exporter:
#    image: prom/snmp-exporter
#    container_name: snmp_exporter
#    restart: unless-stopped
#    volumes:
#      - ./snmp-exporter/:/etc/snmp_exporter/
#    ports:
#      - "9116:9116"
#    depends_on:
#      - prometheus

